modes:
    decoder:
        host: proxy.green-rabbit.net
        port: 30002

database:
    host: proxy.green-rabbit.net
    port: 5432
    name: flight_weather
    user: postgres
    pass: postgres

filter:
    area:
        lat:
            ref: 35.682677
        lon:
            ref: 139.762230

        distance: 100

font:
    path: ./font
    map:
        jp_medium: migmix-1p-regular.ttf
        jp_bold: migmix-1p-bold.ttf

webapp:
    static_dir_path: react/dist

liveness:
    file:
        collector: /dev/shm/modes-sensing/liveness/collector
        receiver: /dev/shm/modes-sensing/liveness/receiver

slack:
    from: ModeS sensing

    bot_token: xoxp-XXXXXXXXXXXX-XXXXXXXXXXXX-XXXXXXXXXXXXX-XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

    error:
        channel:
            name: "#error"
            id: C04Q1CEGW9K
        interval_min: 180
