decoder:
    modes:
        host: proxy.green-rabbit.net
        port: 30002
    # vdl2:  # オプション: VDL2 データソースを使用する場合に指定
    #     host: 192.168.0.20
    #     port: 5050

database:
    host: proxy.green-rabbit.net
    port: 5432
    name: flight_weather
    user: postgres
    pass: postgres

filter:
    area:
        lat:
            ref: 35.682677
        lon:
            ref: 139.762230

        distance: 100

font:
    path: ./font
    map:
        jp_medium: migmix-1p-regular.ttf
        jp_bold: migmix-1p-bold.ttf

webapp:
    static_dir_path: react/dist
    cache_dir_path: cache

liveness:
    file:
        collector: /dev/shm/modes-sensing/liveness/collector
        receiver:
            modes: /dev/shm/modes-sensing/liveness/modes
            # vdl2: /dev/shm/modes-sensing/liveness/vdl2  # decoder.vdl2 設定時のみ
    schedule:
        daytime:
            start_hour: 7
            end_hour: 22
            timeout_sec: 60 # 1分以内にデータ受信がなければ異常
        nighttime:
            timeout_sec: 3600 # 1時間以内にデータ受信がなければ異常

slack:
    from: ModeS sensing

    bot_token: xoxp-XXXXXXXXXXXX-XXXXXXXXXXXX-XXXXXXXXXXXXX-XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

    error:
        channel:
            name: "#error"
            id: C04Q1CEGW9K
        interval_min: 60
